version: '3.1'

services:
  gobarber_db:
    container_name: 'gobarber_db'
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: gostack_gobarber
    ports:
      - 5432:5432

  # gobarber_adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
